### PR TITLE
[UPDATE]: General Update (2)

### PR DESCRIPTION
**Pull request by Simperfy**
UPDATE: Hero images
FIX: Gallery page react errors
UPDATE: Removed dependecy 'react-responsive'
FIX: Collage image responsiveness

### CODE REVIEW

**Comment by DauntlessDev** [comment]
All are good! Just need to hide the register button until before the date of reg, and the speakers section 🤩

**Review by DauntlessDev — CHANGES_REQUESTED** [review]
I just noticed. the responsiveness of the speakers part can still be improved which will also improve the other sections dependent on it (faculty and committee section). Thanks

image

**Comment by Simperfy** [comment]
> I just noticed. the responsiveness of the speakers part can still be improved which will also improve the other sections dependent on it (faculty and committee section). Thanks
> 
> image

done

**Review by DauntlessDev — APPROVED** [review]
Great job!! 😋🥳

**Pull request merged**
