### PR TITLE
Feat about

### PR DESCRIPTION
**Pull request by Grymleth**
Thank you @Simperfy for the reusable component.

### CODE REVIEW

**Comment by Grymleth** [comment]
Need to update placeholder urls to HTTPS.

**Comment by Simperfy** [comment]
> Need to update placeholder urls to HTTPS.

You can convert to draft instead, no need to close.

**Comment by Grymleth** [comment]
Teach me

**Comment by Simperfy** [comment]
image

**Comment by Grymleth** [comment]
> Click "convert to draft" in upper right. image

thank you very much.

**Review by DauntlessDev — APPROVED** [review]

**Pull request merged**
